# Generated by Django 3.1.2 on 2020-10-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_signing', models.DateField(verbose_name='Дата подписания')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование Организации')),
                ('director', models.CharField(max_length=100, verbose_name='Генеральный директор')),
                ('legal_address', models.CharField(max_length=254, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='E-mail')),
                ('number_of_contract', models.CharField(max_length=250, verbose_name='Номер договора')),
                ('terms', models.TextField(null=True, verbose_name='Содержание договора')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('file', models.FileField(blank=True, upload_to='static/upload', verbose_name='Прикрепленный файл')),
                ('period_of_execution', models.DateField(verbose_name='Срок выполнения')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('На этапе оплаты', 'На этапе оплаты'), ('На этапе подписывания', 'На этапе подписывания')], default='На этапе подписывания', max_length=21, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='WorkOrService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100, verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Услуга или работа',
                'verbose_name_plural': 'Услуги или работы',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_period', models.DateField(verbose_name='Срок исполнения')),
                ('subject', models.CharField(max_length=200, verbose_name='Количество товара')),
                ('payment_period', models.DateField(verbose_name='Срок оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма')),
                ('penalty', models.FloatField(verbose_name='Неустойка')),
                ('reaction', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Не выполнено', max_length=12, verbose_name='Реакция')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_organization', models.CharField(max_length=100, verbose_name='Название организации')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('name_of_the_contract', models.CharField(max_length=100, verbose_name='Наименование договора')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('number_of_contract', models.TextField(max_length=100, verbose_name='Номер договора')),
                ('date_of_signing', models.DateField()),
                ('period_of_execution', models.DateField()),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('share_of_payment', models.CharField(max_length=100, verbose_name='Доли платежа')),
                ('term', models.DateField()),
                ('other_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conditions', verbose_name='Иные условия')),
                ('subject_of_a_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workorservice', verbose_name='Предмет договора')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='subject_of_a_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workorservice', verbose_name='Предмет договора'),
        ),
    ]
