# Generated by Django 3.1.2 on 2020-10-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
    ]
