# Generated by Django 3.1.2 on 2020-10-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timing',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
