# Generated by Django 3.1.2 on 2020-10-23 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201023_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='today',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
