# Generated by Django 3.1.2 on 2020-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_timing_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='part_of_amount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='part_of_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='quality',
        ),
        migrations.AlterField(
            model_name='timing',
            name='penalty',
            field=models.FloatField(default=0.0, verbose_name='Неустойка'),
        ),
    ]
