# Generated by Django 3.1.2 on 2020-10-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201023_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
