# Generated by Django 3.1.2 on 2020-10-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201023_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='quality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.quality'),
            preserve_default=False,
        ),
    ]
