# Generated by Django 3.1.2 on 2020-10-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
    ]
