# Generated by Django 3.1.2 on 2020-10-26 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_filesadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='name',
            field=models.CharField(default='Компьютеры', max_length=120, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(default='Компьютеры', max_length=120, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='execution_period',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='payment_period',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='quality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.quality'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='subject',
            field=models.CharField(default='0', max_length=200, verbose_name='Количество товара'),
        ),
    ]
