# Generated by Django 3.1.2 on 2020-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201026_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='execution_period',
            field=models.DateField(verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='payment_period',
            field=models.DateField(verbose_name='Срок оплаты'),
        ),
    ]
