# Generated by Django 3.1.2 on 2020-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201026_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Дни разницы'),
        ),
        migrations.AddField(
            model_name='timing',
            name='delivered',
            field=models.IntegerField(default=0, verbose_name='Доставлено'),
        ),
        migrations.AddField(
            model_name='timing',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Заплачено'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Неустойка'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='subject',
            field=models.IntegerField(verbose_name='Количество обещанного товара'),
        ),
    ]
