# Generated by Django 3.1.2 on 2020-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201027_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Оплачено'),
        ),
    ]
